apiVersion: apps/v1
kind: Deployment
metadata:
  name: led
spec:
  replicas: 1
  selector:
    matchLabels:
      app: led
  template:
    metadata:
      labels:
        app: led
    spec:
      containers:
      - image: okteto.dev/ray:latest
        name: led
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/L-html.zip"
        - name: Vless_UUID
          value: "077189f0-9b3b-4a55-8e7e-af874a24c952"
        - name: Vless_Path
          value: "/app"
        - name: Vmess_UUID
          value: "077189f0-9b3b-4a55-8e7e-af874a24c952"
        - name: Vmess_Path
          value: "/-vmess"
        - name: Share_Path
          value: "/crtbnmiirtr"
